services:
  elm327-emulator:
    build: .
    container_name: elm327-emulator

    ports:
      - "35000:35000"

    environment:
      PORT: 35000
      SCENARIO: car

    volumes:
      - ./emulator/elm/scenarios:/app/elm/scenarios

    stdin_open: true
    tty: true

    restart: unless-stopped